### PR TITLE
Prompt Featured Added

### PR DESCRIPTION
**Pull request by thisEqualsThat**
Included inquirer library to developed prompt capability. Added sinon to work with ava test framework together supporting stubs and mock testing.  Created promptPresenter and add prompt function to display interface. Defined a InquirerPrompt interface in Command.

### CODE REVIEW

**Comment by unional** [comment]
Thanks!

In general, this looks pretty nice. One issue to consider is that "Display" doesn't have prompt, e.g. it doesn't make sense for `InMemoryDisplay` to have a prompt method.

I think it should be separated from Display and live in some input device.

**Comment by thisEqualsThat** [comment]
Yes!!! I realized this issue, when I went through the preexisted test cases. In my design, I have to create an empty prompt function for InMemoryDisplay and CompositeDisplay. It makes no sense. I should take it out as a separated interface. Also I didn't came up a good way to test my groupPromptsCommand under /test/command.ts, since it's async. This is my first time code in typescript. Took me a while to get my hands on.

**Comment by unional** [comment]
Hope you enjoying it. :) TypeScript is just JavaScript. My recommendation is to try using it like so. Let the compiler/language service to do the work for inferring types most of the time, and define the type only when you need to.

Consider the types you define is there to help to clarify your intent and/or help the compiler a little bit when it gets things wrong.

**Comment by unional** [comment]
@thisEqualsThat wish you are all well.
I have made a lot of changes to the code and just added the prompt feature.

Normally I would ask to see if you can rebase your changes so that I can merge this PR instead,
but since my change to the underlying code base is substantial, it is much easier to create a new one.

Thanks for your contribution and wish you all the best.

**Pull request closed without merging**
